columns:
  latitude: latitude
  longitude: longitude
  request_timestamp: creation_timestamp
  timestamp_columns: [creation_timestamp, completion_timestamp, wind_timestamp]
  h3_index: h3_level8_index
  direct_identifiers: [notification_number, reference_number]
  drop_columns: ["Unnamed: 0"]

suburb:
  name: "ROBINVALE"    # seen on the public map https://odp-cctegis.opendata.arcgis.com/datasets/
  name_column: OFC_SBRB_NAME
  query_url: "https://citymaps.capetown.gov.za/agsext/rest/services/Theme_Based/Political_Administrative_Boundaries/MapServer/4/query" # 4 correspond to official suburbs
  cache_path: data/official_suburbs.geojson
  projected_crs: EPSG:32734
  radius_metres: 1852.0   # ~ 1 arcmin

